name: Deployment/Update

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 12 * * *" #runs at 00:00 UTC everyday
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Fetch data from Conseil Constitutionnel website
        run: |
          pip3 install -r requirements.txt
          python prepare_data.py

      - name: Install dependancies
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: yarn install
          
      - name: Build
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: yarn build
          
      - name: Deploy to Infomaniak
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "build/"
          REMOTE_HOST: 464i8.ftp.infomaniak.com
          REMOTE_USER: 464i8_ci
          TARGET: /home/clients/04cd6fa9bfb5342793851e99c0041e14/sites/parrainages2022

      - name: Notify on success
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://api.pushover.net/1/messages.json
          json: |
            {
              "token": "${{ secrets.PUSHOVER_TOKEN }}",
              "user": "${{ secrets.PUSHOVER_USER }}",
              "message": "L'application 'parrainages2022.princelle.org' a bien été mise à jour."
            }
      - name: Notify on failure
        if: ${{ failure() }}
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://api.pushover.net/1/messages.json
          json: |
            {
              "token": "${{ secrets.PUSHOVER_TOKEN }}",
              "user": "${{ secrets.PUSHOVER_USER }}",
              "message": "Erreur lors de la mise à jour de 'parrainages2022.princelle.org'."
            }
